### PR TITLE
update regex_comments string in check-script-has-no-table-name

### LINKED ISSUE #46: Regex Parsing Leads to Hanging Test
**Describe the bug**

When attempting to run `check-script-has-no-table-name`, the test can hang, potentially due to [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html). 

**To Reproduce**

I have yet to determine exact triggers but have spot-checked the regex and a test string both on [regex101.com](regex101.com) and in my dbt codebase.

String 1:
```
{#
test
#}

WITH source AS (
  SELECT *
  FROM {{ source('schema','table') }}
)
SELECT
, a
, b
FROM source
```
causes "catastrophic backtracking" and the test to hang when executed in my codebase

Screen Shot 2021-12-17 at 6 12 19 PM

but a string
```
{#
test
#}

WITH source AS (
  SELECT *
  FROM {{ source('schema','table') }}
)
SELECT
, a
FROM source
```
does not in both my codebase and regex101.com

Screen Shot 2021-12-17 at 6 12 25 PM

**Expected behavior**

The regex to parse in a manner that doesn't cause the test to hang. 

**Version:**
v1.0.0

**Additional context**

This bug was introduced when the regex [here](https://github.com/offbi/pre-commit-dbt/blob/41003145b5cd67601fa0f3b6bb98ca3247543446/pre_commit_dbt/check_script_has_no_table_name.py#L13) was updated in [this commit](https://github.com/offbi/pre-commit-dbt/commit/65a38ad5a195a183722b98f77dce411a92c0e1c8)

### PR DESCRIPTION
**Pull request by neddonaldson**
fixes #46

### CODE REVIEW

**Comment by neddonaldson** [comment]
hey @tomsej wanted to call your attention to this, which solves what may also be a blocker for some other folks trying to upgrade to v1.0.0

**Comment by tomsej** [comment]
Sorry @neddonaldson . I was solving some family issues. Will look into this tomorrow!

**Comment by neddonaldson** [comment]
@tomsej no need to apologize! Appreciate you taking a look

**Comment by tomsej** [comment]
Hi @neddonaldson, thank you for this PR! It is tricky! But your regex is much better than mine. Unfortunately  `test_replace_comments` is failing on 
```
sql = "/* select * from ee*/"
assert replace_comments(sql) == ""
```

It is returning "/**/". Think fixing the test is enough since `replace_comment` is used only for ignoring table names in comments so it does not matter if it is returning blank comments. Can you please fix the falling test? Thank you!

**Comment by neddonaldson** [comment]
@tomsej ready for your eyes again. Just added an option for the test to pass with "/**/" per your note that "it does not matter if it is returning blank comments". Passed locally but it doesn't look like I can run workflows to check in github actions
Screen Shot 2022-01-26 at 10 22 56 AM

**Comment by tomsej** [comment]
Thank you @neddonaldson looks good! Hope new version will be released soon

**Pull request merged**
