### PR TITLE
Fix/dbt parse config

### PR DESCRIPTION
**Pull request by pgoslatara**
Adding fixes to `dbt-parse` as suggested [here](https://github.com/dbt-checkpoint/dbt-checkpoint/pull/195#issuecomment-2054067866) in #195 by @jaklan. Note that I've retained `add_dbt_cmd_model_args` so that I can run `dbt-parse` like this:
```yaml
- id: dbt-parse
  args: ["++threads", "64", "--"]
```

### CODE REVIEW

**Comment by jaklan** [comment]
@pgoslatara I'm not a specialist in the `dbt-checkpoint` codebase, but looking at:
```
def add_dbt_cmd_model_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--model-prefix",
        type=str,
        default="",
        help="Prefix dbt selector, for selecting parents.",
    )
    parser.add_argument(
        "--model-postfix",
        type=str,
        default="",
        help="Postfix dbt selector, for selecting children.",
    )
    parser.add_argument(
        "--models",
        nargs="*",
        help="""pre-commit-dbt is by default running changed files.
        If you need to override that, e.g. in case of Slim CI (state:modified),
        you can use this option.""",
    )
```
and
```
def add_dbt_cmd_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--global-flags",
        nargs="*",
        help="""Global dbt flags applicable to all subcommands.
        Instead of dash `-` please use `+`.""",
    )
    parser.add_argument(
        "--cmd-flags",
        nargs="*",
        help="Command-specific dbt flags. Instead of dash `-` please use `+`.",
    )
```    

I believe `add_dbt_cmd_model_args` should be removed, and your example would look like:
```
- id: dbt-parse
  args: ["--cmd-flags", "++threads", "64", "--"]
```

**Comment by BAntonellini** [comment]
Both approaches are valid, passing `--cmd-flags` is more verbose, that's all.

So far, `dbt-xxx` hooks are being used with `--cmd-flags` as @jaklan stated, and almost all are loading `add_dbt_cmd_model_args ` as well.

**Comment by jaklan** [comment]
@BAntonellini the ones which don't use these flags, like `dbt clean` or `dbt deps`, don't load

**Comment by BAntonellini** [comment]
@jaklan what do you mean by those hooks `don't load`?

```shell
✗ pre-commit 
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/bruno/.cache/pre-commit/patch1713464420-77963.
dbt clean................................................................Failed
- hook id: dbt-clean
- exit code: 1

Executing cmd: `dbt clean --project-dir transform`
18:20:22  Running with dbt=1.7.7
18:20:22  Encountered an error:
Runtime Error
  dbt will not clean the following directories outside the project: [.....]

dbt deps.................................................................Passed
```

**Comment by jaklan** [comment]
These hooks don't load `add_dbt_cmd_model_args` as these commands don't use any models args - and it should be the same with `dbt parse`

**Comment by BAntonellini** [comment]
Now I see, and agree with your point. Although it doesn't "break" anything, having `add_dbt_cmd_model_args` is useless in this case.

@pgoslatara I'd remove model args, leave only `add_dbt_cmd_args` and pass any desired flag via `--cmd-flags ++some-flag`

**Comment by pgoslatara** [comment]
> Now I see, and agree with your point. Although it doesn't "break" anything, having `add_dbt_cmd_model_args` is useless in this case.
> 
> @pgoslatara I'd remove model args, leave only `add_dbt_cmd_args` and pass any desired flag via `--cmd-flags ++some-flag`

Thanks for the input on this @jaklan and @BAntonellini, I'm still getting used to this code base so always happy to have a helping hand.

I removed `add_dbt_cmd_model_args` in 60b1489. What confuses me is that I now need to call `dbt-parse` like this:
```yaml
    - id: dbt-parse
      args: ["--cmd-flags", "++threads", "64"]
```

When I can call `dbt-compile` like this:
```yaml
    - id: dbt-compile
      args: ["++threads", "64", "--"]
```

**Comment by jaklan** [comment]
@pgoslatara isn't that a side-effect of that code?
```
def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser()
    add_filenames_args(parser)
    add_dbt_cmd_args(parser)
    add_dbt_cmd_model_args(parser)
    add_config_args(parser)
```
and
```
    def add_filenames_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "filenames",
        nargs="*",
        help="Filenames pre-commit believes are changed.",
    )
 ```
 
It seems the parser treats `++threads` as a filename and appends it to the final command. You can try to add `"--model-postfix", "+"` to args, if my assumption is true - that should fail with something like `unrecognised argument: threads+` (sorry, I can't test it by myself at the moment).

**Comment by jaklan** [comment]
Hm, maybe I was too fast with the outcome, because filenames don't go through `get_flags()` which is responsible for replacing `+` with `-` - in that case I would expect output like:
```
The selection criterion '++threads' does not match any nodes
No nodes selected!
```

**Pull request merged**
