### PR TITLE
improve `get missing filepaths` utils logic

### PR DESCRIPTION
**Pull request by BAntonellini**
Replaced simple string work of `get_missing_file_paths` utils function for a proper pathlib.Path approach.

With these:
- Only existent files are added to hooks
- dbt project must no longer be nested in a subfolder: it can be at the same level of pre-commit-config.yml, or in any level of depth

### CODE REVIEW

**Comment by katieclaiborne** [comment]
@BAntonellini, is this improvement intended to resolve #101?

I found that pinning our pre-commit hooks to [c3c3f1d](https://github.com/dbt-checkpoint/dbt-checkpoint/pull/105/commits/c3c3f1dbbb6e4aa9ac282dff8f42b5d7324f9acb) resolved the issue, but didn't know if that was what you had in mind.

I did notice a seemingly transient `IsADirectoryError` in `check-model-columns-have-desc`, but wasn't sure if that was related to your changes.

```
Check the model columns have description.................................Failed
- hook id: check-model-columns-have-desc
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoo9i55a7s/py_env-python3/bin/check-model-columns-have-desc", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoo9i55a7s/py_env-python3/lib/python3.10/site-packages/pre_commit_dbt/check_model_columns_have_desc.py", line 93, in main
    status_code, _ = check_column_desc(paths=args.filenames, manifest=manifest)
  File "/home/runner/.cache/pre-commit/repoo9i55a7s/py_env-python3/lib/python3.10/site-packages/pre_commit_dbt/check_model_columns_have_desc.py", line [41](https://github.com/cityblock/data-platform/actions/runs/4408977134/jobs/7724690930#step:11:42), in check_column_desc
    for item in itertools.chain(models, schemas):
  File "/home/runner/.cache/pre-commit/repoo9i55a7s/py_env-python3/lib/python3.10/site-packages/pre_commit_dbt/utils.py", line 201, in get_model_schemas
    with open(yml_file, "r") as file:
IsADirectoryError: [Errno 21] Is a directory: 'dbt/target/run/data_platform/models/staging/example/_example__models.yml'

**Comment by BAntonellini** [comment]
@katieclaiborne thanks for pointing that issue out, this PR is originally intended to solve what was proposed on PR #99 

I've just committed a fix that should solve what you mentioned, as it's related with all these changes. Could you please try with https://github.com/dbt-checkpoint/dbt-checkpoint/pull/105/commits/3a31b0be972392a7a56823086822338efdf553cd ?

Thank you

**Comment by katieclaiborne** [comment]
That worked! Thank you, Bruno.

Did I also see you [mention](https://github.com/dbt-checkpoint/dbt-checkpoint/pull/99#issuecomment-1466290774) that v1.1 would be released this week?

**Comment by BAntonellini** [comment]
Great to hear that!

Yes, we are working some final details, and will release 1.1

**Pull request merged**
