### PR TITLE
Fix: Add .dbt-checkpoint.yaml to disable hook execution tracking in mixpanel

### PR DESCRIPTION
**Pull request by mbhoopathy**
Fix: Add `.dbt-checkpoint.yaml` to disable hook execution tracking in mixpanel

## Description & motivation
- updated` flake8` github repo link in the pre-commit-config.yaml
- updated `mirrors-mypy` version and added `additional_dependencies` in the pre-commit-config.yaml
- ignored mypy errors in `utils.py` and `check_model_has_description.py`
- added `--valid_config` as an input argument to 
         `test_check_model_has_meta_keys.py`
         `test_check_model_has_description.py`
         `test_check_model_columns_have_desc.py`
         
## Validation of models:
Results of `pytest`
image

Results of `pre-commit run `
image

## Checklist:

- [x] My pull request represents one logical piece of work.
- [x] My commits are related to the pull request and look clean.
- [ ] I have updated the README file.

### CODE REVIEW

**Review by BAntonellini — APPROVED** [review]
looks good to me

**Comment by mbhoopathy** [comment]
The CI job run didn't trigger any tracking event in Mixpanel, fix is working as expected. Merging into main.

**Comment by aiwithwhitehat** [comment]
Where can I find the documentation for adding this?
@BAntonellini @mbhoopathy 
The reason for these updates needs to be clearer esp. `disable-tracking`

**Comment by mbhoopathy** [comment]
hi @anks2024 
My apologies, if the reasoning provided was not clear enough

Reason: @BAntonellini brought it to our attention that hooks executions/runs were getting tracked in Mixpanel which is something we wanted to prevent from happening, hence added `.dbt-checkpoint.yaml` to disable tracking.

**Comment by aiwithwhitehat** [comment]
Even after adding the disabled tracking, I feel it still [fails](https://github.com/dbt-checkpoint/dbt-checkpoint/issues/127) 

And it is caught in my system just because of Enterprise VPN. So it seems like `disable-tracking: true` doesn't work as expected.

The admin will have to add Mixpanel to the Allow List explicitly. Is that expected?

**Comment by mbhoopathy** [comment]
> Even after adding the disabled tracking, I feel it still [fails](https://github.com/dbt-checkpoint/dbt-checkpoint/issues/127)
> 
> And it is caught in my system just because of Enterprise VPN. So it seems like `disable-tracking: true` doesn't work as expected.
> 
> The admin will have to add Mixpanel to the Allow List explicitly. Is that expected?

I'd suggest to open an issue with more details (possibly a screenshot) to get this reviewed by the data-coves team.

**Comment by BAntonellini** [comment]
> Even after adding the disabled tracking, I feel it still [fails](https://github.com/dbt-checkpoint/dbt-checkpoint/issues/127)
> 
> And it is caught in my system just because of Enterprise VPN. So it seems like `disable-tracking: true` doesn't work as expected.
> 
> The admin will have to add Mixpanel to the Allow List explicitly. Is that expected?

@anks2024 I've just verified that having `disable-tracking: true` in your `.dbt-checkpoint.yml` config file skips reaching out to Mixpanel at all.

```python
ipdb> self.disable_tracking
True
```

In the `dbtCheckpointTracking` class ([here](https://github.com/dbt-checkpoint/dbt-checkpoint/blob/main/dbt_checkpoint/tracking.py#L34)) the Mixpanel class is never instantiated and the track never performed.

Quick note: make sure:
1. the `.dbt-checkpoint.yml` config file is located in the same directory as where you run pre-commit from, next to `.pre-commit-config.yaml`
2. you are using latest dbt-checkpoint ref: `v2.0.1`

image
image

**Pull request merged**
