### PR TITLE
BugFix: Fixes the ymls having a different folder structure as compared to the sqls

### PR DESCRIPTION
**Pull request by sfc-gh-pkommini**
- Remove the root_folder prefix as that is causing an error while fetching yml files causing a crash in `dbt-checkpoint`

### CODE REVIEW

**Comment by sfc-gh-afedorov** [comment]
don't think we can add reviewers @sfc-gh-pkommini, but @JFrackson seems like he might be able to help here

**Comment by sfc-gh-pkommini** [comment]
Should fix #98. Any chance you can review @JFrackson?

**Comment by sfc-gh-pkommini** [comment]
cc @ssassi @BAntonellini Is it possible to review?

**Comment by BAntonellini** [comment]
@sfc-gh-pkommini the logic of `root_folder = Path(node["root_path"]).name` is intended to obtain the last component of `root_path`, be it dbt project root.

With it, alongside model's `patch_path` we construct the entire Path where to find the respective YML of the sql file

Could you tell us how your project structure is? Are you running pre-commit from INSIDE the dbt project? 
Thanks.

**Comment by sfc-gh-pkommini** [comment]
@BAntonellini 

I have a dbt `models` directory structure like so:

Model files:
- `models/dir1/sub_dir1/model_a.sql`,
- `models/dir1/sub_dir1/model_b.sql`,
- `models/dir1/sub_dir1/model_c.sql`

Model properties file: `models/dir1/sub_dir1/models_schema.yml` looks like this:
```yml
version: 2
models:
  - name: model_a
    description: "Something something a"

  - name: model_b
    description: "Something something b"

  - name: model_c
    description: "Something something c"
```
When I run this command from project home
```bash
pre-commit run check-model-has-meta-keys --files models/dir1/sub_dir1/model_a.sql
```

And I get this error:
```
Check the model has keys in the meta part................................Failed
- hook id: check-model-has-meta-keys
- exit code: 1

Traceback (most recent call last):
  File "/Users/xxx/.cache/pre-commit/repo4nh1q0_n/py_env-python3.10/bin/check-model-has-meta-keys", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/.cache/pre-commit/repo4nh1q0_n/py_env-python3.10/lib/python3.10/site-packages/pre_commit_dbt/check_model_has_meta_keys.py", line 99, in main
    return has_meta_key(
  File "/Users/xxx/.cache/pre-commit/repo4nh1q0_n/py_env-python3.10/lib/python3.10/site-packages/pre_commit_dbt/check_model_has_meta_keys.py", line 53, in has_meta_key
    in_schemas = {
  File "/Users/xxx/.cache/pre-commit/repo4nh1q0_n/py_env-python3.10/lib/python3.10/site-packages/pre_commit_dbt/check_model_has_meta_keys.py", line 53, in <setcomp>
    in_schemas = {
  File "/Users/xxx/.cache/pre-commit/repo4nh1q0_n/py_env-python3.10/lib/python3.10/site-packages/pre_commit_dbt/utils.py", line 199, in get_model_schemas
    with open(yml_file, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'project-name/models/dir1/sub_dir1/models_schema.yml'
```

But I do have that file with the structure as seen above. What am I doing wrong?

If I either remove or comment out the models a, b, c from the properties file, then it works and passes the `check-model-has-meta-keys` check.

I believe it's failing on this line specifically of the `check_model_has_meta_keys.py`
```python
    schemas = get_model_schemas(list(ymls.values()), filenames)
```

which in turn calls:
```python
def get_model_schemas(
    yml_files: Sequence[Path], filenames: Set[str], all_schemas: bool = False
) -> Generator[ModelSchema, None, None]:
    for yml_file in yml_files:
        with open(yml_file, "r") as file:
            schema = yaml.safe_load(file)
            for model in schema.get("models", []):
                if isinstance(model, dict) and model.get("name"):
                    model_name = model.get("name", "")  # pragma: no mutate
                    if model_name in filenames or all_schemas:
                        yield ModelSchema(
                            model_name=model_name,
                            file=yml_file,
                            filename=yml_file.stem,
                            schema=model,
                        )
```


Also, I ran the same code with the change (made the change in my local directory structure `/Users/xxx/.cache/pre-commit/repo4nh1q0_n/py_env-python3.10/lib/python3.10/site-packages/pre_commit_dbt/check_model_has_meta_keys.py` and `utils.py`) in the PR above and it fixed the issue.

In this code below:
```python
def has_meta_key(
    paths: Sequence[str],
    manifest: Dict[str, Any],
    meta_keys: Sequence[str],
    allow_extra_keys: bool,
) -> int:
    paths = get_missing_file_paths(paths, manifest)

    status_code = 0
    ymls = get_filenames(paths, [".yml", ".yaml"])
    sqls = get_model_sqls(paths, manifest)
```
the `ymls` has the following value:

```
{'models_schema': PosixPath(project-name/models/dir1/sub_dir1/models_schema.yml')}
```

But the `sqls` has the value:

```
{'model_a': PosixPath('models/dir1/sub_dir1/model_a.sql')}
```
Notice the `project-name` in the `ymls` but not present in the `sqls`.

Why the difference? Why does one have the `project-name` prefixing the path and one doesn't?

Let me know if this helps?

**Comment by sfc-gh-pkommini** [comment]
> @sfc-gh-pkommini the logic of `root_folder = Path(node["root_path"]).name` is intended to obtain the last component of `root_path`, be it dbt project root.
> 
> With it, alongside model's `patch_path` we construct the entire Path where to find the respective YML of the sql file

That path is currently what is causing the `FileNotFoundError`.

> Could you tell us how your project structure is? Are you running pre-commit from INSIDE the dbt project? Thanks.
Yes. I'm running from inside the project. More details here #98

**Comment by sfc-gh-pkommini** [comment]
@BAntonellini Do you need any other details from me?

**Comment by sfc-gh-pkommini** [comment]
@ssassi @BAntonellini @JFrackson Any of you have bandwidth to review this?

**Comment by sfc-gh-pkommini** [comment]
Also note that I don't get the error when the dbt model doesn't have an entry in the `models_schema.yml` properties file. It's only when a given model has an entry in the properties file.

**Comment by sfc-gh-pkommini** [comment]
Hi Folks,

@BAntonellini Did you get a chance to review this?

**Comment by BAntonellini** [comment]
Hi @sfc-gh-pkommini 

We've modified utils functionality when discovering sql/yml equivalent filepaths, what should fix your situation.

Until we publish v1.1 this week, you can work using `c3c3f1dbbb6e4aa9ac282dff8f42b5d7324f9acb` as pre-commit-config rev

```yaml
repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: c3c3f1dbbb6e4aa9ac282dff8f42b5d7324f9acb

    hooks:
      [...]
```

Your proposed solution would've broken use cases in which the dbt project is located in a subfolder

Let us know your results if you test, thank you for contributing

**Comment by sfc-gh-pkommini** [comment]
@BAntonellini Confirming that the bug was fixed.

**Pull request closed without merging**
